workflows:
    sample-workflow:
      name: Codemagic Sample Workflow
      max_build_duration: 120                  #build duration in minutes
      instance_type: mac_mini_m1
      scripts: 
        - name : test dir
          script: |
             pod --version
             pwd
             ls -l /Users/builder/clone
        - name : test clone
          script: |
             git clone https://github.com/sadiq638/calcproject.git
             git clone https://github.com/sadiq638/crudapi.git
             pwd
             cd calcproject
             pwd
             cd ..
             pwd
             cd ..
             pwd
             cd clone 
             ls -l

